[package]
name = "chemistry_consts"
version = "0.1.5"
edition = "2021"
license = "MIT"
description = "A library for most constants in chemistry"
repository = "https://github.com/um-univie/chemistry_consts/"
readme = "README.md"
